# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nimble-123.skills-hub
PackageVersion: 0.4.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimble-123/skills-hub/releases/download/v0.4.0/skills-hub_0.4.0_x64-setup.exe
  InstallerSha256: 526DC4D555BB036287DB9F1B6854C920FEB8A0DB2EF54E1B0DF975544FD0A14B
  ProductCode: skills-hub
ManifestType: installer
ManifestVersion: 1.12.0
